import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0e0e0e',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#131313',
        'surface-container': '#1a1919',
        'surface-container-high': '#201f1f',
        'surface-container-highest': '#262626',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-variant': '#262626',
        'surface': '#0e0e0e',
        'surface-tint': '#00d4ff',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#adaaaa',
        'outline': '#777575',
        'outline-variant': '#494847',
        primary: '#00d4ff',
        'primary-fixed': '#00d2fd',
        'primary-fixed-dim': '#00c3eb',
        'primary-container': '#00d4ff',
        'on-primary': '#004c5e',
        'on-primary-fixed': '#002c37',
        'on-primary-fixed-variant': '#004c5d',
        'on-primary-container': '#004352',
        secondary: '#ac8aff',
        'secondary-fixed': '#dac9ff',
        'secondary-fixed-dim': '#ceb9ff',
        'secondary-container': '#5516be',
        'on-secondary': '#280067',
        'on-secondary-fixed': '#40009b',
        'on-secondary-fixed-variant': '#5f28c8',
        'on-secondary-container': '#d9c8ff',
        tertiary: '#c5ffc9',
        'tertiary-fixed': '#6bff8f',
        'tertiary-fixed-dim': '#5bf083',
        'tertiary-container': '#6bff8f',
        'on-tertiary': '#00692c',
        'on-tertiary-fixed': '#004a1d',
        'on-tertiary-fixed-variant': '#006a2d',
        'on-tertiary-container': '#005f28',
        error: '#ff716c',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        'inverse-surface': '#fcf8f8',
        'inverse-on-surface': '#565554',
        'inverse-primary': '#00677e',
      },
      fontFamily: {
        headline: ['Orbitron', 'sans-serif'],
        body: ['Rajdhani', 'sans-serif'],
        label: ['Rajdhani', 'sans-serif'],
        brand: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
};
export default config;
